import type { Metadata } from "next";
import "../../public/vars.scss";
import "./globals.css";
import { Header } from "@/widgets/header/Header";

export const metadata: Metadata = {
  title: "Royal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
          {children}
      </body>
    </html>
  );
}
